[http]
port = 8080
secrets = "PEGt1nnBNQObvnXJwVrec8fKNVM64spK/eYCw6OyEbE="

[redis]
host = '127.0.0.1'
port = 6379
db = 0
prefix = 'ashoka/'
pool-size = 12

[postgresql]
host = '127.0.0.1'
port = 5432
db = 'ashoka'
user = 'postgres'
password = ''
pool-size = 18

[rabbitmq]
host = '127.0.0.1'
port = 5672
user = 'guest'
password = 'guest'
virtual-host = 'ashoka'
pool-size = 18

[twilio]
account-sid = 'change-me'
auth-token = 'change-me'
from = '+1...'

[crawler]
google = "https://www.google.com/"
