SET(CMAKE_SYSTEM_NAME WINDOWS_STORE)
SET(CMAKE_SYSTEM_VERSION 8.1)

SET(CROSSTOOL_PREFIX x86_64-w64-mingw32)

SET(CMAKE_C_COMPILER   ${CROSSTOOL_PREFIX}-gcc)
SET(CMAKE_CXX_COMPILER ${CROSSTOOL_PREFIX}-g++)
