[crawlers_logs]
"find.by-name" = "SELECT body, created_at FROM crawlers_logs WHERE name = $1 ORDER BY created_at DESC LIMIT 1"
"insert" = "INSERT INTO crawlers_logs(name, url, body) VALUES($1, $2, $3)"
